# ARRAY

In [11]:
import numpy as np 
#One way to define array
x = [1,2,3,4]

y= np.array(x)

print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [3]:
import numpy as np 
#One way to define array
y= np.array([1,2,3,4])
#this print function will show direct the element of array 
print(y)
#this y will show the type -->array
y

[1 2 3 4]


array([1, 2, 3, 4])

In [9]:
#taking user input in the array
l = []

for i in range(1,5):
    int_1 = int(input("enter :"))  #adding int in the input will not make this str
    l.append(int_1)

print(np.array(l))  #this will return the string if no int in input

enter : 4
enter : 5
enter : 3
enter : 5


[4 5 3 5]


In [ ]:
#Dimensions of Array
[1 3 5 6]
[[1 3 5 7]]
[[[3 6 7 7 3]]]
#name.ndim --> for Dimension of array 

In [19]:
ar2= np.array([[1,3,2,4],[1,2,3,4]])
print(ar2)
print("Dimensions :",ar2.ndim)

[[1 3 2 4]
 [1 2 3 4]]
Dimensions : 2


In [27]:
ar3= np.array([[[1,3,2,4],[1,2,3,4],[3,5,62,4]]])
print(ar3)
print("Dimensions :",ar3.ndim)

[[[ 1  3  2  4]
  [ 1  2  3  4]
  [ 3  5 62  4]]]
Dimensions : 3


In [41]:
#Create a array with input Dimension
arn = np.array([1,2,6,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 6 4]]]]]]]]]]
10


# ZEROS

In [49]:
ar_zeros = np.zeros(5)
ar_zeros1 = np.zeros((3,5))

print(ar_zeros)
print()
print(ar_zeros1)
print(ar_zeros1.ndim)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2


# ONES array

In [55]:
ar_one = np.ones(4)
ar_one1 = np.ones((3,5))

print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [57]:
#Empty array 

ar=np.empty(8)
print(ar)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [59]:
# Range in array

ar = np.arange(3)
print(ar)

[0 1 2]


In [73]:
##   Array With Diogonal Element filled with Zeros

ar=np.eye(3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
# LineSpace Function

ar = np.linspace(1,10,6)
print(ar)

[ 1.   2.8  4.6  6.4  8.2 10. ]


## 0-Create Numpy array with Random Numbers
# rand()
# randn()
# ranf()
# randint()

# Rand()  ->>> return between 0---1
np.random.rand(number)

In [77]:
var = np.random.rand(5)
print(var)

[0.09337945 0.50938244 0.05196162 0.81578353 0.58536252]


In [81]:
var1 = np.random.rand(3,5)
print(var1)

[[0.53813778 0.52190448 0.59199534 0.07070733 0.55696875]
 [0.31355055 0.55530307 0.32258004 0.30311747 0.83527536]
 [0.69592136 0.50305222 0.31137838 0.14711463 0.63841939]]


#  randn() ->>> -ve +ve both 

In [83]:
var = np.random.randn(5)
print(var)

[-0.29789172  1.65767959  0.04843906 -0.514677    1.18854259]


In [85]:
var = np.random.randn(2,5)
print(var)

[[ 0.5908123   0.58429016  0.41416636  0.61500069 -0.42845358]
 [ 1.38673656 -0.02641854 -0.40700843 -0.02345276 -0.33741796]]


# ranf() ...>>> lessthan 1 close zero  [0.0,1.0)

In [87]:
var = np.random.ranf(5)
print(var)

[0.43749515 0.30885832 0.33097775 0.17314683 0.3756677 ]


In [95]:
var = np.random.ranf(5)
print(var)

[0.20130749 0.85648134 0.98969451 0.91653942 0.54708189]


# Randint()----------->

In [105]:
var = np.random.randint(1,100,100).reshape(10,10)
print(var)

[[20 67 17 47 58 35 10  8 24  9]
 [38 53  3 53 55 39  2 98  2 19]
 [46 36 65 63  2 15 52 14 20 75]
 [23 16  5 56  2 67 50 89 46 52]
 [13 72  1 97 58 79 50 92 46 99]
 [67 11 21  7  7 21  5  5 64 25]
 [50 73 52 51 57 99 19 16 45  6]
 [70 30 23 93 81 94 34 30 66 47]
 [74  5 17 14 53 56 78 20 63 43]
 [49 18 22 80 28 81 64 13  9 73]]
