# DataType

In [3]:
import numpy as np
x = np.array([1,2,3,4,5])
print("DataType of x :",x.dtype)

DataType of x : int32


In [5]:
x = np.array(['a','b','t'])
print("DataType of x :",x.dtype)

DataType of x : <U1


# HOW TO ASSIGN DATATYPE IN ARRAY

In [21]:
a = np.array([1,2,3,4,5])
x = np.array([1,2,3,4,5], dtype = np.int8)
print(a)
print("DataType before x :",a.dtype)
print("DataType after x :",x.dtype)

[1 2 3 4 5]
DataType before x : int32
DataType after x : int8


In [ ]:
x = np.array([1,2,3,4,5], dtype = float32)
print(x)
print("DataType before x :",x.dtype)

# DATATYPE CONVERSION

In [23]:
s = np.array([1,2,3,5])
new = np.float32(s)

print(s)
print("DataType of s :",s.dtype)
print(new)
print("DataType of new :",new.dtype)

[1 2 3 5]
DataType of s : int32
[1. 2. 3. 5.]
DataType of new : float32
