# SHAPE AND RESHAPING IN NUMPY ARRAYS

In [3]:
import numpy as np
var1 = np.array([[1,2],[1,2]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
print(var1.shape)
print(var2.shape)

[[1 2]
 [1 2]]

[[1 2 3 4]
 [1 2 3 4]]

(2, 2)
(2, 4)


In [28]:
var = np.array([1,2,3,4], ndmin = 4)
print(var)
print("Dimension of var is : ",var.ndim)
print()
print("Shape of Var is : ",var.shape)

[[[[1 2 3 4]]]]
Dimension of var is :  4

Shape of Var is :  (1, 1, 1, 4)


# How to reshape array

variable_name.reshape(number of rows, number of elements)

In [52]:
arr = np.array([1,2,3,4,5,6,7,8])

x = arr.reshape(4,2)
print("One Dimension array : ",arr)
print()
print("Two dimension array as (Per Reshape(4,2) : \n", x)


One Dimension array :  [1 2 3 4 5 6 7 8]

Two dimension array as (Per Reshape(4,2) : 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [113]:
arr = np.array([2,3,4,5,6,7,8,9,21,32,1,23])

x = arr.reshape(2,3,2)
print(x)
print(x.ndim)
print()
x = arr.reshape(2,2,3)
print(x)
print(x.ndim)
print()
#change to one
one = x.reshape(-1)
print(one)
print(one.ndim)

[[[ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [21 32]
  [ 1 23]]]
3

[[[ 2  3  4]
  [ 5  6  7]]

 [[ 8  9 21]
  [32  1 23]]]
3

[ 2  3  4  5  6  7  8  9 21 32  1 23]
1


# Arithmetic Operations

In [122]:
var = np.array([2,3,45,5])

var1 = var + 5
print(var)

[ 2  3 45  5]


In [162]:
a = np.array([1,2,3,4])
b = np.array([9,8,7,6])
add = a+b
print(add)

[10 10 10 10]


In [7]:
a = np.array([1,2,3,4])
b = np.array([9,8,7,6])

varAdd = np.add(a,b)
varSub = np.subtract(a,b)
varMul = np.multiply(a,b)
varDiv = np.divide(a,b)
varMod = np.mod(a,b)
varPow = np.power(a,b)
varRec = np.reciprocal(a,b)

In [158]:
print(varAdd) 

[10 10 10 10]


In [124]:
print(varSub)

[-8 -6 -4 -2]


In [144]:
print(varPow)

[   1  256 2187 4096]


In [150]:
print(varMod)

[1 2 3 4]


In [152]:
print(varDiv)

[0.11111111 0.25       0.42857143 0.66666667]


In [154]:
print(varMul)

[ 9 16 21 24]


In [156]:
print(varRec)

[1 0 0 0]


# 2D Array

In [168]:
a = np.array([[1,2,3,4],[9,8,7,6]])
b = np.array([[9,8,7,6],[1,2,3,4]])
add = a+b
print(add)

[[10 10 10 10]
 [10 10 10 10]]


In [176]:
var = np.array([1,2,3,4])
print(np.min(var))
print(np.max(var))

1
4


# position of max and min
Index of element np.argmx

In [188]:
var = np.array([2,3,1,4,1])
print(np.min(var), np.argmin(var), np.argmax(var))

1 2 3


In [ ]:
# axis in 2D array
axis = 0 ----> col
axis = 1 ----> row

In [200]:
var = np.array([[2,3,1,4,1],[33,34,64,4,1]])
print (np.min(var,axis=0))
#sqrt
print("Square of array elements")
print(np.sqrt(var))

[2 3 1 4 1]
Square of array elements
[[1.41421356 1.73205081 1.         2.         1.        ]
 [5.74456265 5.83095189 8.         2.         1.        ]]


# Trignometry

In [204]:
var = np.array([1,2,3,5,7])
print(np.sin(var))

[ 0.84147098  0.90929743  0.14112001 -0.95892427  0.6569866 ]


In [206]:
var = np.array([1,2,3,5,7])
print(np.cumsum(var))

[ 1  3  6 11 18]


# BroadCasting in Numpy array

In [213]:
var = np.array([1,2,3,5,7])
var1 = np.array([1,2,3,4])
print(var+var1)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [ ]:
#this is Broadcasting error

In [215]:
var = np.array([1,2,3,5,7])
var1 = np.array([1,2,3,4,3])
print(var+var1)

[ 2  4  6  9 10]


In [ ]:
# this Works Because of same number of elements in the array

# Array Shapes

In [222]:
var1 = np.array([1,2,3])
print("This array is (1x3) : ")
print(var1)
print()
var2 = np.array([[1],[2],[3]])
print("This array is (3x1) : ")
print(var2)

This array is (1x3) : 
[1 2 3]

This array is (3x1) : 
[[1]
 [2]
 [3]]


In [224]:
#Added 1x3 and 3x1
var1 = np.array([1,2,3])
var2 = np.array([[1],[2],[3]])
print(var1+var2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [226]:
#Added 1x3 and 2x1
var1 = np.array([1,2,3])
var2 = np.array([[1],[3]])
print(var1+var2)

[[2 3 4]
 [4 5 6]]


In [236]:
#Added 1x3 and 1x1
var1 = np.array([1,2,3])
var2 = np.array([[3]])
varAdd = var1 + var2
print(varAdd)
print(np.ndim(varAdd))

[[4 5 6]]
2


In [238]:
#Added 1x3 and 1x1
var1 = np.array([1,2,3])
var2 = np.array([3])
varAdd = var1 + var2
print(varAdd)
print(np.ndim(varAdd))

[4 5 6]
1


In [240]:
var1 = np.array([1,2,3])
var2 = np.array([3,4])
varAdd = var1 + var2
print(varAdd)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
# Why BroadCasting Error 
when you are doing operations In both arrays
there must be be 1Xany pr anyX1 